# Generated by Django 5.2 on 2025-05-28 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('estado_curso', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosDeEstudiantes',
            fields=[
                ('id_estudiante', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('numero_comision', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dia1', models.CharField(blank=True, max_length=20, null=True)),
                ('dia2', models.CharField(blank=True, max_length=20, null=True)),
                ('dia3', models.CharField(blank=True, max_length=20, null=True)),
                ('horario1', models.CharField(blank=True, max_length=20, null=True)),
                ('horario2', models.CharField(blank=True, max_length=20, null=True)),
                ('horario3', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_comision', models.CharField(max_length=50)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.datosdeestudiantes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
