# Generated by Django 5.2 on 2025-05-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
