# Generated by Django 5.2 on 2025-06-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_datosdeestudiantes_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('comision', models.IntegerField()),
                ('numero_clase', models.IntegerField()),
                ('nombre_clase', models.CharField(max_length=100)),
                ('fecha_clase', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionAlumno',
            fields=[
                ('valoracion_alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.CharField(max_length=10)),
                ('id_usuario', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('preferencia_clase', models.CharField(choices=[('me_gusto', 'Me gustó'), ('mas_o_menos', 'Más o menos'), ('no_me_gusto', 'No me gustó')], max_length=20)),
                ('rol_profe', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('plataforma', models.IntegerField()),
                ('streaming', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.clase')),
            ],
        ),
    ]
