# Generated by Django 5.2 on 2025-06-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_clase_valoracionalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
