# Generated by Django 5.2 on 2025-06-05 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_curso_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c1', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c10', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c11', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c12', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c13', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c14', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c15', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c3', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c4', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c5', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c6', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c7', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c8', to='plataforma.comision'),
        ),
        migrations.AddField(
            model_name='datosdeestudiantes',
            name='cursando9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c9', to='plataforma.comision'),
        ),
    ]
