# Generated by Django 5.2 on 2025-06-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_datosdeestudiantes_cursando1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdeestudiantes',
            name='cursando10',
        ),
        migrations.RemoveField(
            model_name='datosdeestudiantes',
            name='cursando11',
        ),
        migrations.RemoveField(
            model_name='datosdeestudiantes',
            name='cursando12',
        ),
        migrations.RemoveField(
            model_name='datosdeestudiantes',
            name='cursando13',
        ),
        migrations.RemoveField(
            model_name='datosdeestudiantes',
            name='cursando14',
        ),
        migrations.RemoveField(
            model_name='datosdeestudiantes',
            name='cursando15',
        ),
    ]
