# Generated by Django 5.2 on 2025-06-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_remove_datosdeestudiantes_cursando10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
