# Generated by Django 5.2 on 2025-06-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_curso_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
