# Generated by Django 5.2 on 2025-06-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_curso_icono1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='icono1',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
    ]
