# Generated by Django 5.2 on 2025-06-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_alter_curso_icono1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='icono1',
            new_name='icono01',
        ),
        migrations.AddField(
            model_name='curso',
            name='icono02',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono03',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono04',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono05',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono06',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono07',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono08',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono09',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono10',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono11',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono12',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
    ]
