# Generated by Django 5.2 on 2025-06-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_rename_icono1_curso_icono01_curso_icono02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='estado_comision',
            field=models.CharField(choices=[('proximo', 'Próximo'), ('en_curso', '¡En curso!'), ('finalizado', 'Finalizado')], default='proximo', max_length=20),
        ),
    ]
