# Generated by Django 5.2 on 2025-06-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_alter_comision_estado_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado_curso',
            field=models.CharField(choices=[('proximo', 'Próximo'), ('en_curso', '¡En curso!'), ('finalizado', 'Finalizado')], default='proximo', max_length=20),
        ),
    ]
