# Generated by Django 5.2 on 2025-06-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_alter_curso_estado_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(choices=[('0.5hs', '0.5 hs'), ('1hs', '1 hs'), ('1.5hs', '1.5 hs'), ('2hs', '2 hs'), ('2.5hs', '2.5 hs'), ('3hs', '3 hs')], default='proximo', max_length=20),
        ),
    ]
