# Generated by Django 5.2 on 2025-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_remove_clase_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado_clase',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
