# Generated by Django 5.2 on 2025-06-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0019_clase_estado_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='plataforma.curso'),
        ),
    ]
