# Generated by Django 5.2 on 2025-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0021_remove_clase_id_clase_id_clase_clasecomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='id_clase',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
