# Generated by Django 5.2 on 2025-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0022_alter_clase_id_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id_clase',
        ),
        migrations.AddField(
            model_name='clase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
