# Generated by Django 5.2 on 2025-06-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0023_remove_clase_id_clase_clase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='id_clase',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
