# Generated by Django 5.2 on 2025-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0024_clase_id_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id',
        ),
        migrations.AlterField(
            model_name='clase',
            name='id_clase',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
