# Generated by Django 5.2 on 2025-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0028_remove_clase_id_clase_clase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='ppt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
