# Generated by Django 5.2 on 2025-06-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0029_clase_ppt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fecha_clase',
        ),
    ]
