# Generated by Django 5.2 on 2025-06-12 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0031_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecomision',
            name='perfil_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
