# Generated by Django 5.2 on 2025-06-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0032_clasecomision_perfil_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_marcada', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('curso', models.CharField(max_length=200)),
                ('comision', models.CharField(max_length=10)),
                ('nombre_clase', models.CharField(max_length=200)),
                ('fecha_clase', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.datosdeestudiantes')),
            ],
            options={
                'unique_together': {('estudiante', 'clase')},
            },
        ),
    ]
