# Generated by Django 5.2 on 2025-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0033_asistenciaclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecomision',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
