# Generated by Django 5.2 on 2025-06-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0034_clasecomision_hora_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(max_length=255)),
                ('opcion_d', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(choices=[('a', 'Opción A'), ('b', 'Opción B'), ('c', 'Opción C'), ('d', 'Opción D')], max_length=1)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.clase')),
            ],
        ),
    ]
