# Generated by Django 5.2 on 2025-06-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0035_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_inicial', models.IntegerField(default=0)),
                ('puntaje_maximo', models.IntegerField(default=0)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.datosdeestudiantes')),
            ],
            options={
                'unique_together': {('estudiante', 'clase')},
            },
        ),
    ]
