# Generated by Django 5.2 on 2025-06-19 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0036_puntajequiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('link_github', models.URLField(blank=True, null=True)),
                ('link_pages', models.URLField(blank=True, null=True)),
                ('link_servidor', models.URLField(blank=True, null=True)),
                ('link_adicional', models.URLField(blank=True, null=True)),
                ('archivo_1', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('archivo_2', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('archivo_3', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entregas/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='entregas/videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='entregas/audios/')),
                ('comentarios_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.comision')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.datosdeestudiantes')),
            ],
        ),
    ]
