# Generated by Django 5.2 on 2025-06-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0037_entregaproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='consigna_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
