# Generated by Django 5.2 on 2025-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0038_curso_consigna_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaproyecto',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaproyecto',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
