# Generated by Django 5.2 on 2025-06-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0039_entregaproyecto_feedback_entregaproyecto_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('online_vivo', 'Online en vivo'), ('online_grabado', 'Online grabado'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='online_vivo', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='entregaproyecto',
            unique_together={('estudiante', 'comision')},
        ),
    ]
