# Generated by Django 5.2 on 2025-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0040_curso_modalidad_curso_precio_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='duracion_clase',
            field=models.CharField(choices=[('0.5hs', '0.5 hs'), ('1hs', '1 hs'), ('1.5hs', '1.5 hs'), ('2hs', '2 hs'), ('2.5hs', '2.5 hs'), ('3hs', '3 hs')], default='2hs', help_text='Duración estimada de cada clase', max_length=20),
        ),
    ]
