# Generated by Django 5.2 on 2025-06-23 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0041_comision_duracion_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'Chat General'), ('comision', 'Chat Comisión'), ('privado', 'Chat Privado')], max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.comision')),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='chat_archivos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='plataforma.chat')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
