# Generated by Django 5.2 on 2025-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0042_chat_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_typing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
