# Generated by Django 5.2 on 2025-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0043_perfilusuario_ultimo_typing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
