# Generated by Django 5.2 on 2025-06-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0044_mensaje_destacado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaclase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asistenciaclase',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.comision'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaclase',
            unique_together={('estudiante', 'clase', 'comision')},
        ),
    ]
