# Generated by Django 5.2 on 2025-06-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0045_alter_asistenciaclase_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasecomision',
            name='perfil_usuario',
        ),
    ]
