# Generated by Django 5.2 on 2025-06-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0046_remove_clasecomision_perfil_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puntajequiz',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='puntajequiz',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.comision'),
        ),
        migrations.AlterUniqueTogether(
            name='puntajequiz',
            unique_together={('estudiante', 'clase', 'comision')},
        ),
    ]
