# Generated by Django 5.2 on 2025-06-30 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0047_alter_puntajequiz_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntajequiz',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.comision'),
        ),
    ]
