# Generated by Django 5.2 on 2025-06-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0048_alter_puntajequiz_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionalumno',
            name='comision_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='valoracionalumno',
            name='curso_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='valoracionalumno',
            name='curso_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='valoracionalumno',
            name='nombre_clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='valoracionalumno',
            name='numero_clase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='valoracionalumno',
            index=models.Index(fields=['curso_id'], name='plataforma__curso_i_d6e123_idx'),
        ),
        migrations.AddIndex(
            model_name='valoracionalumno',
            index=models.Index(fields=['comision_id'], name='plataforma__comisio_913ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='valoracionalumno',
            index=models.Index(fields=['id_estudiante'], name='plataforma__id_estu_2efe0a_idx'),
        ),
        migrations.AddIndex(
            model_name='valoracionalumno',
            index=models.Index(fields=['numero_clase'], name='plataforma__numero__73d6f9_idx'),
        ),
    ]
