# Generated by Django 5.2 on 2025-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0049_valoracionalumno_comision_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionClaseGratis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dias', models.CharField(max_length=255)),
                ('horarios', models.CharField(max_length=255)),
                ('nivel_pc', models.IntegerField()),
                ('exp_programacion', models.CharField(max_length=100)),
                ('nivel_programacion', models.IntegerField()),
                ('tecnologias', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
