# Generated by Django 5.2 on 2025-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0051_lecturamensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaRegistroPagoCompleta',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estudiante', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('plataforma', models.CharField(max_length=30)),
                ('medio_pago', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('id_transaccion', models.CharField(max_length=100)),
                ('link_comprobante', models.URLField(blank=True, null=True)),
                ('archivo_comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('nombre_comision', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_registro_pago_completa',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono01',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono02',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono03',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono04',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono05',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono06',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono07',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono08',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono09',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono10',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono11',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono12',
            field=models.FileField(blank=True, null=True, upload_to='iconos_cursos/'),
        ),
    ]
