# Generated by Django 5.2 on 2025-07-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0052_vistaregistropagocompleta_alter_curso_icono01_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=30)),
                ('medio_pago', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('id_transaccion', models.CharField(max_length=100)),
                ('link_comprobante', models.URLField(blank=True, null=True)),
                ('archivo_comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.comision')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.datosdeestudiantes')),
            ],
        ),
    ]
