# Generated by Django 5.2 on 2025-07-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0053_registropago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
