# Generated by Django 5.2 on 2025-11-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0055_mensaje_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='plataforma.comision'),
        ),
    ]
