# Generated by Django 5.2 on 2025-11-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0056_alter_chat_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionIAPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dias', models.CharField(help_text='Ej: Lunes,Miércoles', max_length=255)),
                ('horarios', models.CharField(help_text='Ej: Mañana,Tarde', max_length=255)),
                ('nivel_pc', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('exp_programacion', models.CharField(choices=[('Sí, tengo experiencia.', 'Sí, tengo experiencia.'), ('He aprendido algo, pero no soy experto.', 'He aprendido algo, pero no soy experto.'), ('No tengo experiencia.', 'No tengo experiencia.')], max_length=120)),
                ('nivel_programacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscripción IA Promo',
                'verbose_name_plural': 'Inscripciones IA Promo',
                'ordering': ['-creado'],
            },
        ),
    ]
