# Generated by Django 5.2 on 2025-11-27 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0057_inscripcioniapromo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcionclasegratis',
            options={'ordering': ['-creado'], 'verbose_name_plural': 'Inscripciones Clase Gratuita - Desarrollo Web'},
        ),
        migrations.AlterModelOptions(
            name='inscripcioniapromo',
            options={'ordering': ['-creado'], 'verbose_name': 'Inscripción IA Promo', 'verbose_name_plural': 'Inscripciones Clase Gratuita - Inteligencia Artificial'},
        ),
        migrations.AddField(
            model_name='inscripcionclasegratis',
            name='dni',
            field=models.CharField(blank=True, default='00000000', help_text='DNI o pasaporte', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscripcionclasegratis',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='inscripcionclasegratis',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], default='Prefiero no decir', max_length=30),
        ),
        migrations.AddField(
            model_name='inscripcionclasegratis',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscripcioniapromo',
            name='dni',
            field=models.CharField(blank=True, default='00000000', help_text='DNI o pasaporte (sin puntos)', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscripcioniapromo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='inscripcioniapromo',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], default='Prefiero no decir', max_length=30),
        ),
        migrations.AddField(
            model_name='inscripcioniapromo',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='dias',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='exp_programacion',
            field=models.CharField(default='No tengo experiencia.', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='horarios',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='nivel_pc',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='nivel_programacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='pais',
            field=models.CharField(default='Argentina', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='tecnologias',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='inscripcionclasegratis',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='dias',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='exp_programacion',
            field=models.CharField(choices=[('Sí, tengo experiencia.', 'Sí, tengo experiencia.'), ('He aprendido algo, pero no soy experto.', 'He aprendido algo, pero no soy experto.'), ('No tengo experiencia.', 'No tengo experiencia.')], default='No tengo experiencia.', max_length=120),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='horarios',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='nivel_pc',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='nivel_programacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='pais',
            field=models.CharField(default='Argentina', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcioniapromo',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
