# Generated by Django 5.2 on 2025-12-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0058_alter_inscripcionclasegratis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprogramacionDeClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha en que se registró la afectación (hoy).')),
                ('estado', models.CharField(choices=[('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada')], max_length=20)),
                ('motivo', models.TextField(help_text='Razón de la ausencia del profesor.')),
                ('nueva_fecha_o_info', models.CharField(blank=True, help_text='Detalles de la nueva fecha o instrucción.', max_length=255, null=True)),
                ('notificado_correo', models.BooleanField(default=False, help_text='Indica si el correo ya fue enviado por el script.')),
                ('clase_afectada', models.ForeignKey(help_text='La clase original (de la tabla ClaseComision) que fue afectada.', on_delete=django.db.models.deletion.CASCADE, to='plataforma.clasecomision')),
            ],
        ),
    ]
