# Generated by Django 5.2 on 2025-12-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0059_reprogramaciondeclase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reprogramaciondeclase',
            options={'verbose_name_plural': 'Reprogramaciones de Clase'},
        ),
        migrations.AlterUniqueTogether(
            name='reprogramaciondeclase',
            unique_together={('clase_afectada',)},
        ),
        migrations.AddField(
            model_name='reprogramaciondeclase',
            name='accion_solicitada',
            field=models.CharField(choices=[('1', 'Mover 1 Clase Siguiente'), ('2', 'Mover 2 Clases Siguientes'), ('3', 'Mover 3 Clases Siguientes'), ('4', 'Mover 4 Clases Siguientes'), ('Cancelada', 'Cancelar Clase')], default='NO_APLICA', max_length=10, verbose_name='Acción Solicitada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprogramaciondeclase',
            name='estado_final',
            field=models.CharField(choices=[('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada')], default='NO_APLICA', max_length=20, verbose_name='Estado Final de la Clase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprogramaciondeclase',
            name='fecha_reprogramada',
            field=models.DateField(blank=True, help_text='Fecha a la que se movió la clase (si aplica).', null=True),
        ),
        migrations.AddField(
            model_name='reprogramaciondeclase',
            name='motivo_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Adicional'),
        ),
        migrations.AddField(
            model_name='reprogramaciondeclase',
            name='motivo_principal',
            field=models.CharField(default='PENDIENTE', max_length=50, verbose_name='Motivo Principal (Select)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reprogramaciondeclase',
            name='clase_afectada',
            field=models.ForeignKey(help_text='Clase original afectada (ClaseComision).', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_reprogramacion', to='plataforma.clasecomision'),
        ),
        migrations.AlterField(
            model_name='reprogramaciondeclase',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró el evento.'),
        ),
        migrations.AlterField(
            model_name='reprogramaciondeclase',
            name='notificado_correo',
            field=models.BooleanField(default=False, help_text='True cuando el correo haya sido enviado.'),
        ),
        migrations.RemoveField(
            model_name='reprogramaciondeclase',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reprogramaciondeclase',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='reprogramaciondeclase',
            name='nueva_fecha_o_info',
        ),
    ]
