# Generated by Django 5.2 on 2025-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0060_alter_reprogramaciondeclase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reprogramaciondeclase',
            options={'ordering': ['-fecha_registro'], 'verbose_name_plural': 'Reprogramaciones de Clase'},
        ),
        migrations.AddField(
            model_name='reprogramaciondeclase',
            name='fecha_original',
            field=models.DateField(blank=True, help_text='Fecha original de la clase antes de reprogramar (para el correo)', null=True),
        ),
    ]
