# Generated by Django 5.2 on 2025-12-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0061_alter_reprogramaciondeclase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAusenciaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('clase_comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.clasecomision')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.datosdeestudiantes')),
            ],
            options={
                'unique_together': {('estudiante', 'clase_comision')},
            },
        ),
    ]
