# Generated by Django 5.2 on 2025-12-12 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0062_notificacionausenciaenviada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicion', models.CharField(help_text='Ejemplo: #52', max_length=10, unique=True)),
                ('titulo_novedad', models.CharField(help_text='Título principal de la novedad destacada', max_length=200)),
                ('extracto_novedad', models.TextField(help_text='Breve descripción de la novedad (1-2 párrafos)')),
                ('link_novedad', models.URLField(help_text='Enlace al artículo, video o anuncio completo')),
                ('titulo_promocion', models.CharField(help_text='Ej: 50% OFF en todos los cursos', max_length=200)),
                ('descuento', models.CharField(default='40%', help_text='Ej: 50%, 30%, GRATIS', max_length=20)),
                ('codigo_cupon', models.CharField(help_text='Código que usarán los alumnos al inscribirse', max_length=50)),
                ('fecha_vencimiento', models.CharField(help_text='Ej: 30 de diciembre, Hasta fin de mes', max_length=50)),
                ('link_promocion', models.URLField(help_text='URL directa a la página de cursos o promo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('enviado_el', models.DateTimeField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-creado_el'],
                'constraints': [models.UniqueConstraint(fields=('numero_edicion',), name='unique_numero_edicion')],
            },
        ),
    ]
