# Generated by Django 5.2 on 2026-01-09 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0063_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del cupón (ej: DESC20)', max_length=50, unique=True)),
                ('descuento_porcentaje', models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento (ej: 20 para 20%)')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de validez')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de expiración (opcional)', null=True)),
                ('usos_maximos', models.PositiveIntegerField(default=0, help_text='Máximo de usos (0 = ilimitado)')),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
