# Generated by Django 5.2 on 2026-01-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0066_alter_registropago_link_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='link_comprobante',
            field=models.URLField(blank=True, help_text='URL del comprobante de pago (Mercado Pago - pagos en efectivo)', max_length=1000, null=True),
        ),
    ]
