
# # # """
# # # Django settings for tecnomarema.

# # # Generated by 'django-admin startproject' using Django 5.2.
# # # """

# # from pathlib import Path
# # import os
# # from dotenv import load_dotenv  # ✅ Para leer variables del .env
# # import dj_database_url  # ✅ Para configurar la base de datos desde DATABASE_URL

# # # Cargar variables de entorno
# # load_dotenv()

# # # BASE_DIR es la raíz del proyecto
# # BASE_DIR = Path(__file__).resolve().parent.parent

# # # Seguridad
# # SECRET_KEY = os.getenv('SECRET_KEY')
# # DEBUG = True  # Cambiar a False en producción
# # # ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', '.ngrok-free.app', 'testserver']

# # # CSRF_TRUSTED_ORIGINS = [
# # #     'https://tu-dominio1.com',
# # #     'https://tecnomarema-app.onrender.com',
# # #     'https://tecnomarema.com.ar',
# # #     'https://www.tecnomarema.com.ar',
# # #     'https://891a-148-222-130-44.ngrok-free.app',
# # # ]

# # # Sin http://
# # ALLOWED_HOSTS = [
# #     'tecnomarema-app.onrender.com',
# #     'tecnomarema.onrender.com', 
# #     'tecnomarema.com.ar', 
# #     'www.tecnomarema.com.ar', 
# #     'localhost', 
# #     '127.0.0.1',
# #     '.ngrok-free.app', 
# #     'testserver',
# # ]

# # # Con https://
# # CSRF_TRUSTED_ORIGINS = [
# #     'https://tecnomarema.onrender.com',
# #     'https://tecnomarema.com.ar',
# #     'https://www.tecnomarema.com.ar',
# # ]

# # # Aplicaciones instaladas
# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     'widget_tweaks',
# #     'plataforma',
# #     'channels',

# # ]
# # #channels para chats en tiempo real
# # # Configuración de Channels
# # ASGI_APPLICATION = 'tu_proyecto.asgi.application'  # Crea asgi.py si no existe
# # CHANNEL_LAYERS = {
# #     'default': {
# #         'BACKEND': 'channels_redis.core.RedisChannelLayer',
# #         'CONFIG': {'hosts': [('127.0.0.1', 6379)], },  # Redis local; usa hosted en prod
# #     },
# # }

# # # Middlewares
# # MIDDLEWARE = [
# #     'django.middleware.security.SecurityMiddleware',
# #     'whitenoise.middleware.WhiteNoiseMiddleware', # 👈 Agregá esta línea
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# # # 🚨 SOLUCIÓN 1: LocaleMiddleware DEBE IR AQUÍ 
# #     'django.middleware.locale.LocaleMiddleware', 

# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# # ]

# # ROOT_URLCONF = 'tecnomarema.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [BASE_DIR / 'plataforma' / 'templates'],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #                 'plataforma.context_processors.nombre_usuario',
# #             ],
# #         },
# #     },
# # ]

# # WSGI_APPLICATION = 'tecnomarema.wsgi.application'

# # # # Base de datos
# # # DATABASES = {
# # #     'default': {
# # #         'ENGINE': 'django.db.backends.postgresql',
# # #         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
# # #         'USER': os.getenv('DB_USER', 'postgres'),
# # #         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
# # #         'HOST': os.getenv('DB_HOST', 'localhost'),
# # #         'PORT': os.getenv('DB_PORT', '5432'),
# # #     }
# # # }

# # # # 2. Reemplazá tu bloque de DATABASES por este:
# # # DATABASES = {
# # #     'default': dj_database_url.config(
# # #         # Si existe DATABASE_URL (en Render), la usa. 
# # #         # Si no existe (en tu PC), usa los valores por defecto que ya tenías.
# # #         default=os.getenv('DATABASE_URL', f"postgres://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', '9560')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'tecnomarema')}")
# # #     )
# # # }

# # # ==========================================================
# # # BLOQUE 1: Tu configuración Local (No se toca)
# # # ==========================================================
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
# #         'USER': os.getenv('DB_USER', 'postgres'),
# #         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
# #         'HOST': os.getenv('DB_HOST', 'localhost'),
# #         'PORT': os.getenv('DB_PORT', '5432'),
# #     }
# # }

# # # ==========================================================
# # # BLOQUE 2: Salto de línea y configuración para Render
# # # ==========================================================
# # if os.getenv('DATABASE_URL'):
# #     import dj_database_url
    
# #     DATABASES['default'] = dj_database_url.config(
# #         conn_max_age=600,
# #         ssl_require=True
# #     )

# # # Validación de contraseñas
# # AUTH_PASSWORD_VALIDATORS = [
# #     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
# #     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
# #     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
# #     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# # ]

# # # Internacionalización
# # LANGUAGE_CODE = 'es'
# # # TIME_ZONE = 'UTC'
# # TIME_ZONE = 'America/Argentina/Buenos_Aires' 
# # USE_I18N = True
# # USE_TZ = True

# # # Archivos estáticos
# # # STATIC_URL = 'static/'
# # # STATICFILES_DIRS = [BASE_DIR / 'plataforma' / 'static']

# # # # se agrega esta linea para el servidor de produccion:
# # # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # STATIC_URL = 'static/'
# # STATICFILES_DIRS = [BASE_DIR / 'plataforma' / 'static']
# # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # # 👈 AGREGÁ ESTA LÍNEA:
# # STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # # # Configuración de email
# # # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # # EMAIL_HOST = 'smtp.gmail.com'
# # # EMAIL_PORT = 587
# # # EMAIL_USE_TLS = True
# # # # luego cambiarlos por el .env########################################################################
# # # EMAIL_HOST_USER = 'tecnomarema.ar@gmail.com'
# # # EMAIL_HOST_PASSWORD = 'egkq gbyh epby xmlq'
# # # DEFAULT_FROM_EMAIL = 'tecnomarema.ar@gmail.com'

# # # --- Configuración de email ---
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Opcional mover al .env
# # EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com') # Leer del .env
# # EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587)) # Leer del .env
# # EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true' # Leer del .env

# # # CREDENCIALES (Siempre del .env)
# # EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# # EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# # DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# # # Login/logout
# # AUTH_USER_MODEL = 'plataforma.PerfilUsuario'
# # LOGIN_URL = 'login'
# # LOGIN_REDIRECT_URL = 'mis_cursos'
# # LOGOUT_REDIRECT_URL = 'login'

# # # Subida de imágenes
# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = BASE_DIR / 'media'

# # # ==========================================================
# # # Mercado Pago
# # # ==========================================================
# # MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')
# # MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')

# # if not MERCADOPAGO_PUBLIC_KEY or not MERCADOPAGO_ACCESS_TOKEN:
# #     print("⚠️ Advertencia: Las claves de Mercado Pago no están definidas en el archivo .env")


# #############################################################################################################
# #############################################################################################################
# #############################################################################################################


# """
# Django settings for tecnomarema.
# Generated by 'django-admin startproject' using Django 5.2.
# """

# from pathlib import Path
# import os
# from dotenv import load_dotenv
# import dj_database_url

# # Cargar variables de entorno desde .env
# load_dotenv()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Seguridad
# SECRET_KEY = os.getenv('SECRET_KEY')
# if not SECRET_KEY:
#     raise ValueError("SECRET_KEY no está definida en .env")

# DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'  # Más seguro: lee como string y convierte

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     'tecnomarema-app.onrender.com',
#     'tecnomarema.onrender.com',
#     'tecnomarema.com.ar',
#     'www.tecnomarema.com.ar',
#     '.ngrok-free.app',
#     'testserver',
# ]

# # CSRF (obligatorio para producción con HTTPS)
# CSRF_TRUSTED_ORIGINS = [
#     'https://tecnomarema.onrender.com',
#     'https://tecnomarema.com.ar',
#     'https://www.tecnomarema.com.ar',
#     'https://*.ngrok-free.app',  # Útil para pruebas con ngrok
# ]

# # Aplicaciones instaladas
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'widget_tweaks',
#     'plataforma',
#     'channels',
# ]

# # Configuración de Channels (para chats en tiempo real)
# ASGI_APPLICATION = 'tecnomarema.asgi.application'  # Asegurate de tener asgi.py
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [("127.0.0.1", 6379)],  # Local: Redis en puerto 6379
#             # En producción (Render): usa REDIS_URL de variables de entorno
#             # "hosts": [os.getenv('REDIS_URL')],
#         },
#     },
# }

# # Middlewares
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.locale.LocaleMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'tecnomarema.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'plataforma' / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'plataforma.context_processors.nombre_usuario',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'tecnomarema.wsgi.application'

# # ==========================================================
# # Base de datos - Soporte local + Render (DATABASE_URL)
# # ==========================================================
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
# #         'USER': os.getenv('DB_USER', 'postgres'),
# #         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
# #         'HOST': os.getenv('DB_HOST', 'localhost'),
# #         'PORT': os.getenv('DB_PORT', '5432'),
# #     }
# # }

# # # Si hay DATABASE_URL (Render), la usa automáticamente (sobrescribe lo anterior)
# # DATABASES['default'] = dj_database_url.config(
# #     conn_max_age=600,
# #     conn_health_checks=True,
# #     ssl_require=True if not DEBUG else False
# # )

# # ==========================================================
# # Base de datos - Soporte local + producción (Render/Railway)
# # ==========================================================
# import dj_database_url

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL', None),  # Render lo provee automáticamente
#         conn_max_age=600,
#         conn_health_checks=True,
#         ssl_require=True if not DEBUG else False
#     )
# }

# # Fallback local si no hay DATABASE_URL (tu config actual)
# if 'default' not in DATABASES or not DATABASES['default']:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
#         'HOST': os.getenv('DB_HOST', 'localhost'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }

# # ==========================================================
# # Validación de contraseñas
# # ==========================================================
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]

# # ==========================================================
# # Internacionalización
# # ==========================================================
# LANGUAGE_CODE = 'es'
# TIME_ZONE = 'America/Argentina/Buenos_Aires'
# USE_I18N = True
# USE_TZ = True

# # ==========================================================
# # Archivos estáticos (WhiteNoise para producción)
# # ==========================================================
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'plataforma' / 'static']
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # ==========================================================
# # Archivos subidos (media)
# # ==========================================================
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# # ==========================================================
# # Email
# # ==========================================================
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# # EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# # EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
# # EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# # EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# # DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
# #####################################################################################

# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = 'smtp.resend.com'
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = 'resend'  # Siempre este valor
# # EMAIL_HOST_PASSWORD = os.getenv('RESEND_API_KEY')
# # DEFAULT_FROM_EMAIL = 'Tecno Marema <no-reply@tecnomarema.com.ar>'  # Cambia si verificaste dominio

# # ==========================================================
# # Email - Resend (estable, gratis 3.000/mes, sin bloqueos en Render)
# # ==========================================================
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.resend.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'resend'  # Siempre este valor fijo
# EMAIL_HOST_PASSWORD = os.getenv('RESEND_API_KEY')
# DEFAULT_FROM_EMAIL = 'Tecno Marema <no-reply@tecnomarema.com.ar>'

# # Opcional: Si querés usar el SDK directo de Resend (más rápido)
# # pip install resend
# # En tus vistas, en vez de EmailMultiAlternatives:
# # import resend
# # resend.api_key = os.getenv('RESEND_API_KEY')
# # resend.Emails.send({...})

# if not all([EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL]):
#     print("⚠️ Advertencia: Configuración de email incompleta en .env")


# print("EMAIL CONFIG USADA: Resend (host: smtp.resend.com, port: 587)")

# # ==========================================================
# # Mercado Pago - Switch test/producción
# # ==========================================================
# MERCADOPAGO_MODE = os.getenv('MERCADOPAGO_MODE', 'test')

# if MERCADOPAGO_MODE == 'production':
#     MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
#     MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')
# else:
#     MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
#     MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')

# if not MERCADOPAGO_ACCESS_TOKEN or not MERCADOPAGO_PUBLIC_KEY:
#     print("⚠️ Advertencia: Credenciales de Mercado Pago no definidas en .env")

# # ==========================================================
# # Autenticación personalizada
# # ==========================================================
# AUTH_USER_MODEL = 'plataforma.PerfilUsuario'
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'mis_cursos'
# LOGOUT_REDIRECT_URL = 'login'

# # ==========================================================
# # Default primary key field type
# # ==========================================================
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ==========================================================
# # Debug adicional (opcional - podés borrar cuando estés listo)
# # ==========================================================
# print(f"DEBUG: {DEBUG}")
# print(f"Mercado Pago MODE: {MERCADOPAGO_MODE}")



# """
# Django settings for tecnomarema.
# Generated by 'django-admin startproject' using Django 5.2.
# """

# from pathlib import Path
# import os
# from dotenv import load_dotenv
# import dj_database_url

# # Cargar variables de entorno desde .env
# load_dotenv()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Seguridad
# SECRET_KEY = os.getenv('SECRET_KEY')
# if not SECRET_KEY:
#     raise ValueError("SECRET_KEY no está definida en .env")

# DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     'tecnomarema-app.onrender.com',
#     'tecnomarema.onrender.com',
#     'tecnomarema.com.ar',
#     'www.tecnomarema.com.ar',
#     '.ngrok-free.app',
#     'testserver',
# ]

# CSRF_TRUSTED_ORIGINS = [
#     'https://tecnomarema.onrender.com',
#     'https://tecnomarema.com.ar',
#     'https://www.tecnomarema.com.ar',
#     'https://*.ngrok-free.app',
# ]

# # Aplicaciones instaladas
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'widget_tweaks',
#     'plataforma',
#     'channels',
# ]

# # Configuración de Channels (para chats en tiempo real)
# ASGI_APPLICATION = 'tecnomarema.asgi.application'
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [("127.0.0.1", 6379)],  # Local
#             # En producción Render: descomenta y usa REDIS_URL
#             # "hosts": [os.getenv('REDIS_URL')],
#         },
#     },
# }

# # Middlewares
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.locale.LocaleMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'tecnomarema.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'plataforma' / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'plataforma.context_processors.nombre_usuario',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'tecnomarema.wsgi.application'

# # ==========================================================
# # Base de datos - Soporte local + Render (DATABASE_URL)
# # ==========================================================
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL', None),
#         conn_max_age=600,
#         conn_health_checks=True,
#         ssl_require=True if not DEBUG else False
#     )
# }

# # Fallback local si no hay DATABASE_URL
# if 'default' not in DATABASES or not DATABASES['default']:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
#         'HOST': os.getenv('DB_HOST', 'localhost'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }

# # ==========================================================
# # Validación de contraseñas
# # ==========================================================
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]

# # ==========================================================
# # Internacionalización
# # ==========================================================
# LANGUAGE_CODE = 'es'
# TIME_ZONE = 'America/Argentina/Buenos_Aires'
# USE_I18N = True
# USE_TZ = True

# # ==========================================================
# # Archivos estáticos (WhiteNoise para producción)
# # ==========================================================
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'plataforma' / 'static']
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # ==========================================================
# # Archivos subidos (media)
# # ==========================================================
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# # ==========================================================
# # Email - Mailgun API (funciona en Render FREE - puerto 443, sin bloqueos)
# # ==========================================================
# # No usamos SMTP (bloqueado en free tier)
# # Usamos variables de entorno que YA pusiste en Render

# EMAIL_BACKEND = 'plataforma.mail_backends.MailgunBackend'

# MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY')
# MAILGUN_DOMAIN = os.getenv('MAILGUN_DOMAIN')
# MAILGUN_BASE_URL = os.getenv('MAILGUN_BASE_URL', 'https://api.mailgun.net/v3')

# DEFAULT_FROM_EMAIL = f"Tecno Marema <postmaster@{MAILGUN_DOMAIN}>"

# if MAILGUN_API_KEY and MAILGUN_DOMAIN:
#     print(f"EMAIL CONFIG USADA: Mailgun API (HTTP) - Domain: {MAILGUN_DOMAIN}")
# else:
#     print("⚠️ FALTAN VARIABLES DE MAILGUN EN RENDER (API_KEY o DOMAIN)")

# # ==========================================================
# # Mercado Pago - Switch test/producción
# # ==========================================================
# MERCADOPAGO_MODE = os.getenv('MERCADOPAGO_MODE', 'test')

# if MERCADOPAGO_MODE == 'production':
#     MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
#     MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')
# else:
#     MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
#     MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')

# if not MERCADOPAGO_ACCESS_TOKEN or not MERCADOPAGO_PUBLIC_KEY:
#     print("⚠️ Advertencia: Credenciales de Mercado Pago no definidas en .env")

# # ==========================================================
# # Autenticación personalizada
# # ==========================================================
# AUTH_USER_MODEL = 'plataforma.PerfilUsuario'
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'mis_cursos'
# LOGOUT_REDIRECT_URL = 'login'

# # ==========================================================
# # Default primary key field type
# # ==========================================================
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ==========================================================
# # Debug adicional
# # ==========================================================
# print(f"DEBUG: {DEBUG}")
# print(f"Mercado Pago MODE: {MERCADOPAGO_MODE}")


"""
Django settings for tecnomarema.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

import cloudinary
import cloudinary.uploader
import cloudinary.api

# Cargar variables de entorno desde .env
load_dotenv()

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔥 CONFIG REAL CLOUDINARY (ESTO ES LO QUE TE FALTABA)
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET'),
    secure=True
)

# Seguridad
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY no está definida en .env")

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'tecnomarema-app.onrender.com',
    'tecnomarema.onrender.com',
    'tecnomarema.com.ar',
    'www.tecnomarema.com.ar',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    'testserver',
    'tecnomarema-app-eb5q.onrender.com',
    'tecnomarema.up.railway.app',
    
]

CSRF_TRUSTED_ORIGINS = [
    'https://tecnomarema.onrender.com',
    'https://tecnomarema.com.ar',
    'https://www.tecnomarema.com.ar',
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://tecnomarema.up.railway.app', 
]

# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'plataforma',
    'channels',
    'cloudinary',
    'cloudinary_storage',
]

# Configuración de Channels (para chats en tiempo real)
ASGI_APPLICATION = 'tecnomarema.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],  # Local
            # En producción Render: descomenta y usa REDIS_URL
            # "hosts": [os.getenv('REDIS_URL')],
        },
    },
}

# Middlewares
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tecnomarema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'plataforma' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'plataforma.context_processors.nombre_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'tecnomarema.wsgi.application'

# ==========================================================
# Base de datos - Soporte local + Render (DATABASE_URL)
# ==========================================================
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL', None),
#         conn_max_age=600,
#         conn_health_checks=True,
#         ssl_require=True if not DEBUG else False
#     )
# }

# # Fallback local si no hay DATABASE_URL
# if 'default' not in DATABASES or not DATABASES['default']:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
#         'HOST': os.getenv('DB_HOST', 'localhost'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }

DATABASE_URL = os.getenv('DATABASE_URL', None)

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
        # Neon requiere SSL siempre. Si estamos usando Neon, forzamos SSL aunque DEBUG sea True.
        ssl_require=True if (DATABASE_URL and 'neon.tech' in DATABASE_URL) else (not DEBUG)
    )
}

# Fallback local si no hay DATABASE_URL
if 'default' not in DATABASES or not DATABASES['default']:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'tecnomarema'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }

# ==========================================================
# Validación de contraseñas
# ==========================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==========================================================
# Internacionalización
# ==========================================================
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# ==========================================================
# Archivos estáticos (WhiteNoise para producción)
# ==========================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'plataforma' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'


# ==========================================================
# Archivos subidos (media)
# ==========================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# APPEND_SLASH = True

# STORAGES = {
#     "default": {
#         "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



# ==========================================================
# Email - Brevo API (adaptado, usa HTTP, sin bloqueos en Render free)
# ==========================================================
EMAIL_BACKEND = 'plataforma.mail_backends.BrevoBackend'

BREVO_API_KEY = os.getenv('BREVO_API_KEY')

DEFAULT_FROM_EMAIL = 'tecnomarema.ar@gmail.com'  # Usa el verificado en Brevo

if BREVO_API_KEY:
    print("EMAIL CONFIG USADA: Brevo API (HTTP) - 300/día free")
else:
    print("⚠️ FALTA BREVO_API_KEY EN RENDER")

# ==========================================================
# Mercado Pago - Switch test/producción
# ==========================================================
MERCADOPAGO_MODE = os.getenv('MERCADOPAGO_MODE', 'test')

if MERCADOPAGO_MODE == 'production':
    MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
    MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')
else:
    MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
    MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')

if not MERCADOPAGO_ACCESS_TOKEN or not MERCADOPAGO_PUBLIC_KEY:
    print("⚠️ Advertencia: Credenciales de Mercado Pago no definidas en .env")

# ==========================================================
# Autenticación personalizada
# ==========================================================
AUTH_USER_MODEL = 'plataforma.PerfilUsuario'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'mis_cursos'
LOGOUT_REDIRECT_URL = 'login'

# ==========================================================
# DEBUG MERCADO PAGO (Temporal - para diagnóstico)
# ==========================================================
print("=== MERCADO PAGO CONFIG EN RAILWAY ===")
print(f"MODE: {MERCADOPAGO_MODE}")
print(f"ACCESS_TOKEN definido: {'Sí' if MERCADOPAGO_ACCESS_TOKEN else 'NO'}")
print(f"PUBLIC_KEY definido: {'Sí' if MERCADOPAGO_PUBLIC_KEY else 'NO'}")

if MERCADOPAGO_PUBLIC_KEY:
    print(f"PUBLIC_KEY empieza con: {MERCADOPAGO_PUBLIC_KEY[:15]}...")
else:
    print("❌ PUBLIC_KEY está vacío!")

if MERCADOPAGO_ACCESS_TOKEN:
    print(f"ACCESS_TOKEN empieza con: {MERCADOPAGO_ACCESS_TOKEN[:15]}...")
else:
    print("❌ ACCESS_TOKEN está vacío!")

print("=====================================")

# ==========================================================
# Default primary key field type
# ==========================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================================
# Debug adicional
# ==========================================================
print(f"DEBUG: {DEBUG}")
print(f"Mercado Pago MODE: {MERCADOPAGO_MODE}")