
"""
Django settings for tecnomarema.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

import cloudinary
import cloudinary.uploader
import cloudinary.api

# Cargar variables de entorno desde .env
load_dotenv()

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔥 CONFIG REAL CLOUDINARY (ESTO ES LO QUE TE FALTABA)
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET'),
    secure=True
)

# Seguridad
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY no está definida en .env")

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'tecnomarema-app.onrender.com',
    'tecnomarema.onrender.com',
    'tecnomarema.com.ar',
    'www.tecnomarema.com.ar',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    'testserver',
    'tecnomarema-app-eb5q.onrender.com',
    'tecnomarema.up.railway.app',
    "tecnomarema-app-production.up.railway.app",
    
]

CSRF_TRUSTED_ORIGINS = [
    'https://tecnomarema.onrender.com',
    'https://tecnomarema.com.ar',
    'https://www.tecnomarema.com.ar',
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://tecnomarema.up.railway.app', 
]

# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",
    "django.contrib.sitemaps",
    'widget_tweaks',
    'plataforma',
    'channels',
    'cloudinary',
    'cloudinary_storage',
]

# Configuración de Channels (para chats en tiempo real)
ASGI_APPLICATION = 'tecnomarema.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],  # Local
            # En producción Render: descomenta y usa REDIS_URL
            # "hosts": [os.getenv('REDIS_URL')],
        },
    },
}

# Middlewares
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tecnomarema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'plataforma' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'plataforma.context_processors.nombre_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'tecnomarema.wsgi.application'

# ==========================================================
# Base de datos - Soporte local + Render (DATABASE_URL)
# ==========================================================
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL', None),
#         conn_max_age=600,
#         conn_health_checks=True,
#         ssl_require=True if not DEBUG else False
#     )
# }

# # Fallback local si no hay DATABASE_URL
# if 'default' not in DATABASES or not DATABASES['default']:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'tecnomarema'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
#         'HOST': os.getenv('DB_HOST', 'localhost'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }

DATABASE_URL = os.getenv('DATABASE_URL', None)

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
        # Neon requiere SSL siempre. Si estamos usando Neon, forzamos SSL aunque DEBUG sea True.
        ssl_require=True if (DATABASE_URL and 'neon.tech' in DATABASE_URL) else (not DEBUG)
    )
}

# Fallback local si no hay DATABASE_URL
if 'default' not in DATABASES or not DATABASES['default']:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'tecnomarema'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '9560'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }

# ==========================================================
# Validación de contraseñas
# ==========================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==========================================================
# Internacionalización
# ==========================================================
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# ==========================================================
# Archivos estáticos (WhiteNoise para producción)
# ==========================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'plataforma' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'


# ==========================================================
# Archivos subidos (media)
# ==========================================================
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'   # Ruta del Volume en Railway

# APPEND_SLASH = True

# STORAGES = {
#     "default": {
#         "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# MEDIA_URL = 'https://res.cloudinary.com/'  # se genera automáticamente



# ==========================================================
# Email - Brevo API (adaptado, usa HTTP, sin bloqueos en Render free)
# ==========================================================
EMAIL_BACKEND = 'plataforma.mail_backends.BrevoBackend'

BREVO_API_KEY = os.getenv('BREVO_API_KEY')

DEFAULT_FROM_EMAIL = 'tecnomarema.ar@gmail.com'  # Usa el verificado en Brevo

if BREVO_API_KEY:
    print("EMAIL CONFIG USADA: Brevo API (HTTP) - 300/día free")
else:
    print("⚠️ FALTA BREVO_API_KEY EN RENDER")

# ==========================================================
# Mercado Pago - Switch test/producción
# ==========================================================
MERCADOPAGO_MODE = os.getenv('MERCADOPAGO_MODE', 'test')

if MERCADOPAGO_MODE == 'production':
    MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
    MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')
else:
    MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
    MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')

if not MERCADOPAGO_ACCESS_TOKEN or not MERCADOPAGO_PUBLIC_KEY:
    print("⚠️ Advertencia: Credenciales de Mercado Pago no definidas en .env")

# ==========================================================
# Autenticación personalizada
# ==========================================================
AUTH_USER_MODEL = 'plataforma.PerfilUsuario'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'mis_cursos'
LOGOUT_REDIRECT_URL = 'login'

# ==========================================================
# DEBUG MERCADO PAGO (Temporal - para diagnóstico)
# ==========================================================
print("=== MERCADO PAGO CONFIG EN RAILWAY ===")
print(f"MODE: {MERCADOPAGO_MODE}")
print(f"ACCESS_TOKEN definido: {'Sí' if MERCADOPAGO_ACCESS_TOKEN else 'NO'}")
print(f"PUBLIC_KEY definido: {'Sí' if MERCADOPAGO_PUBLIC_KEY else 'NO'}")

if MERCADOPAGO_PUBLIC_KEY:
    print(f"PUBLIC_KEY empieza con: {MERCADOPAGO_PUBLIC_KEY[:15]}...")
else:
    print("❌ PUBLIC_KEY está vacío!")

if MERCADOPAGO_ACCESS_TOKEN:
    print(f"ACCESS_TOKEN empieza con: {MERCADOPAGO_ACCESS_TOKEN[:15]}...")
else:
    print("❌ ACCESS_TOKEN está vacío!")

print("=====================================")

# ==========================================================
# Default primary key field type
# ==========================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================================
# Debug adicional
# ==========================================================
print(f"DEBUG: {DEBUG}")
print(f"Mercado Pago MODE: {MERCADOPAGO_MODE}")